"""Per-repository behavior switches.

mergedog was originally built for pytorch/pytorch, whose merge workflow has
repository-specific bots, labels, and a known-good branch. Keep those defaults,
but make the policy explicit so other GitHub repos can use the generic parts of
the harness without tripping over PyTorch-only conventions.
"""
from __future__ import annotations

from dataclasses import dataclass

from mergedog.paths import REPO_SLUG, REPO_SSH_URL


@dataclass(frozen=True)
class ProjectPolicy:
    repo_slug: str
    repo_ssh_url: str
    trunk_label: str | None = None
    ci_sev_label: str | None = None
    merging_label: str | None = None
    mergebot_login: str | None = None
    merge_command: str | None = None
    drci_logins: frozenset[str] = frozenset()
    drci_trailer: str | None = None
    known_good_ref: str | None = None
    ci_progress_total_estimate: int | None = None

    @property
    def has_pytorch_merge_bot(self) -> bool:
        return self.mergebot_login is not None and self.merge_command is not None


def get_project_policy() -> ProjectPolicy:
    if REPO_SLUG == "pytorch/pytorch":
        return ProjectPolicy(
            repo_slug=REPO_SLUG,
            repo_ssh_url=REPO_SSH_URL,
            trunk_label="ciflow/trunk",
            ci_sev_label="ci: sev",
            merging_label="merging",
            mergebot_login="pytorchmergebot",
            merge_command="@pytorchbot merge",
            drci_logins=frozenset({"pytorch-bot", "pytorch-bot[bot]"}),
            drci_trailer="automatically generated by Dr. CI",
            known_good_ref="origin/viable/strict",
            # A typical trunk wave is around 180-200 checks. Extra ciflow/*
            # labels may push higher; callers must treat this as a floor, not
            # a cap.
            ci_progress_total_estimate=200,
        )
    return ProjectPolicy(
        repo_slug=REPO_SLUG,
        repo_ssh_url=REPO_SSH_URL,
    )
